services:
  billing-form:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billing-form-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - billing-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  billing-network:
    driver: bridge

volumes:
  billing-data:
    driver: local
